name: Update Space Shooter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-space-shooter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: SuryaNandan07
          output-path: space-shooter.gif
          strategy: random
          fps: 40
